export const teamData = [
  {
    image: "/team/frank.jpeg",
    name: "Frank Alejo Betancur",
    title: "Frontend Engineer",
    desc: "FullStack Padawan and Community builder. Learning.",
    background: "bg-indigo-600/10 dark:bg-indigo-600/30",
    socialNetworks: [
      { name: "linkedin", url: "https://www.linkedin.com/in/frankbetancur/" },
      { name: "twitter", url: "https://x.com/KranK2Me" },
      { name: "github", url: "https://github.com/KranK2Me" },
      { name: "instagram", url: "https://www.instagram.com/elpanda.dev/" },
    ],
    isActive: true,
  },
  {
    image: "/team/mafe.jpeg",
    name: "Mafe Serna",
    title: "Software Developer",
    desc: "Speaker and active participant of the communities.",
    background: "bg-emerald-600/10 dark:bg-emerald-600/30",
    socialNetworks: [
      {
        name: "linkedin",
        url: "https://www.linkedin.com/in/mafesernaarboleda/",
      },
      { name: "twitter", url: "https://x.com/mafesernaarbole" },
      { name: "github", url: "https://github.com/mafesernaarboleda" },
      { name: "instagram", url: "https://www.instagram.com/mafesernaar/" },
      { name: "website", url: "https://mafe.dev/" },
    ],
    isActive: true,
  },
  {
    image: "/team/camilo.jpeg",
    name: "Christian Camilo Galeano",
    title: "Software Developer",
    desc: "Tech and programming enthusiast with a great love for communities 🤝",
    background: "bg-red-600/10 dark:bg-red-600/30",
    socialNetworks: [
      { name: "linkedin", url: "https://www.linkedin.com/in/camilodev/" },
      { name: "instagram", url: "https://www.instagram.com/ch.camilog/" },
    ],
    isActive: true,
  },
  {
    image: "/team/dianella.jpeg",
    name: "Dianella Restrepo Chaverra",
    title: "Systems Engineer",
    desc: "Passion for technology 👩🏻‍💻, active participant in the communities.",
    background: "bg-sky-600/10 dark:bg-sky-600/30",
    socialNetworks: [
      {
        name: "linkedin",
        url: "https://www.linkedin.com/in/dianellarestrepochaverra/",
      },
      { name: "twitter", url: "https://x.com/chzdiane" },
      { name: "instagram", url: "https://www.instagram.com/chzdiane/" },
    ],
    isActive: true,
  },
  {
    image: "/team/maria.png",
    name: "Maria Alejandra Franco",
    title: "Backend Developer",
    desc: "Technology lover 👩🏻‍💻, involved in technology communities.",
    background: "bg-indigo-600/10 dark:bg-indigo-600/30",
    socialNetworks: [
      { name: "linkedin", url: "https://www.linkedin.com/in/mariafrancodev/" },
      { name: "twitter", url: "https://x.com/mariafrancodev" },
      { name: "github", url: "https://github.com/khriztianmoreno" },
      { name: "instagram", url: "https://www.instagram.com/mariafrancodev/" },
    ],
    isActive: true,
  },
  {
    image: "/team/khriztian.jpeg",
    name: "Cristian Moreno",
    title: "FullStack Javascript Developer",
    desc: "Community builder & Javascript Lover 👨🏻‍💻♥️👨🏻‍🏫 ",
    background: "bg-emerald-600/10 dark:bg-emerald-600/30",
    socialNetworks: [
      { name: "linkedin", url: "https://www.linkedin.com/in/khriztianmoreno/" },
      { name: "twitter", url: "https://x.com/khriztianmoreno" },
      { name: "github", url: "https://github.com/khriztianmoreno" },
      { name: "instagram", url: "https://www.instagram.com/khriztianmoreno/" },
      { name: "website", url: "https://khriztianmoreno.dev" },
    ],
    isActive: true,
  },
  {
    image: "/team/adrian.jpeg",
    name: "Adrián Estrada",
    title: "C.T.O.",
    desc: "Developer in love with NodeJS, thirsty for new technologies",
    background: "bg-red-600/10 dark:bg-red-600/30",
    socialNetworks: [
      { name: "linkedin", url: "https://www.linkedin.com/in/edsadr/" },
      { name: "twitter", url: "https://x.com/edsadr" },
      { name: "github", url: "https://github.com/edsadr" },
      { name: "instagram", url: "https://www.instagram.com/edsadr/" },
    ],
    isActive: true,
  },
  {
    image: "/team/ivan.jpeg",
    name: "Ivan Villa",
    title: "Backend Developer",
    background: "bg-sky-600/10 dark:bg-sky-600/30",
    isActive: false,
  },
  {
    image: "/team/alexander.jpeg",
    name: "Alexander Osman",
    title: "Software developerale",
    background: "bg-emerald-600/10 dark:bg-emerald-600/30",
    isActive: false,
  },
  {
    image: "/team/jeny.jpeg",
    name: "Jeny Alejandra Mazo",
    title: "Full-stack Development",
    background: "bg-red-600/10 dark:bg-red-600/30",
    isActive: false,
  },
  {
    image: "/team/alex.jpeg",
    name: "Alex Ramirez",
    title: "Rust Developer",
    background: "bg-sky-600/10 dark:bg-sky-600/30",
    isActive: false,
  },
  {
    image: "/team/julian.jpeg",
    name: "Julián Duque",
    title: "DevRel",
    background: "bg-sky-600/10 dark:bg-sky-600/30",
    isActive: false,
  },
];

export const sponsors = [
  {
    id: 1,
    image: "/sponsors/nodo-eafit.png",
    name: "Nodo Eafit",
    location: "Medellin",
    link: "https://es.nodoeafit.com",
  },
  {
    id: 2,
    image: "/sponsors/softserve.png",
    name: "SoftServe",
    location: "Austin",
    link: "https://www.softserveinc.com",
  },
  {
    id: 3,
    image: "/sponsors/ruta-n.png",
    name: "Ruta N Medellin",
    location: "Medellin",
    link: "https://rutanmedellin.org",
  },
  {
    id: 4,
    image: "/sponsors/jetbrains.png",
    name: "JetBrains",
    location: "Praga",
    link: "https://www.jetbrains.com",
  },
];

export const sponsorPackages = [
  {
    id: 1,
    name: "Bronce",
    priceMonthly: (900000 / 12) * 1.25,
    priceYearly: 900000,
    benefits: [
      "Mención en materiales digitales",
      "Acceso a estadísticas básicas de la comunidad",
    ],
  },
  {
    id: 2,
    name: "Plata",
    priceMonthly: (1700000 / 12) * 1.25,
    priceYearly: 1700000,
    benefits: [
      "Logo en materiales promocionales",
      "Acceso a estadísticas básicas de la comunidad",
      "Espacio para presentación en eventos",
    ],
  },
  {
    id: 3,
    name: "Oro",
    priceMonthly: (3000000 / 12) * 1.25,
    priceYearly: 3000000,
    benefits: [
      "Logo en sitio web y redes sociales",
      "Envio de correos a la comunidad",
      "Publicación de ofertas de trabajo",
      "Talleres o charlas impartidas por la empresa",
    ],
    tag: "Preferido",
  },
  {
    id: 3,
    name: "Conference",
    priceMonthly: 5500000,
    priceYearly: 5500000,
    benefits: [
      "Promoción en la conferencia de JSConf Latam",
      "10 entradas VIP para la conferencia",
      "Patrocinio Plata en MedellinJS",
      "Acceso a estadísticas",
      "Stand en la conferencia",
    ],
  },
];

export const sponsorFaqs = [
  {
    id: 1,
    question: "¿Cuál es el proceso para convertirse en patrocinador?",
    answer:
      "Ponte en contacto con nosotros a través del formulario de contacto y te enviaremos toda la información necesaria.",
  },
  {
    id: 2,
    question: "¿Qué pasa si quiero cambiar de paquete de patrocinio?",
    answer:
      "Puedes cambiar de paquete de patrocinio en cualquier momento. Solo tienes que ponerte en contacto con nosotros.",
  },
  {
    id: 3,
    question: "¿Puedo cancelar mi patrocinio en cualquier momento?",
    answer:
      "Sí, puedes cancelar tu patrocinio en cualquier momento. Solo tienes que ponerte en contacto con nosotros.",
  },
  {
    id: 4,
    question:
      "¿Qué ofrece el plan Conference y en qué se diferencia de los demás?",
    answer:
      "El plan Conference está especialmente diseñado para la JSConf Latam. Incluye promoción exclusiva durante la conferencia, 10 entradas VIP, un stand en el evento y todos los beneficios del plan Plata en MedellínJS. Este plan es ideal para empresas que desean maximizar su visibilidad en uno de los eventos más importantes de la comunidad tech en Latinoamérica..",
  },
  {
    id: 5,
    question: "¿Puedo pagar mensualmente o debo comprometerme a un pago anual?",
    answer:
      "Ofrecemos ambas opciones. Puedes elegir pagar mensualmente con un pequeño incremento del 25% sobre el costo anual, o realizar un pago único anual para ahorrar en el costo total.",
  },
];

export const sponsorTestimonials = [
  {
    description:
      "La conexión establecida con Medellín JS, impacta directamente nuestra estrategia de relacionamiento con partners claves que hacen parte del ecosistema y que activamente entregan valor a nuestra operación.",
    image: "/testimonials/01.jpeg",
    name: "Juan Tobón",
    company: "Softserve",
    description1:
      "La comunidad de MedellínJS es vibrante y altamente cualificada.",
    image1: "/testimonials/02.jpg",
    name1: "Jane Doe",
    company1: "Ruta N",
  },
  {
    description:
      "Patrocinar MedellínJS ha sido clave para nuestra estrategia de employer branding ",
    image: "/testimonials/02.jpg",
    name: "Jane Doe",
    company: "Ruta N",
    description1:
      "Como patrocinadores, hemos encontrado en MedellínJS un aliado estratégico para atraer talento de alto nivel. La posibilidad de publicar nuestras ofertas de trabajo y participar en eventos nos ha permitido reclutar a algunos de los mejores profesionales del sector. ¡Una experiencia que repetiríamos sin dudarlo!",
    image1: "/testimonials/03.jpg",
    name1: "Alice Johnson",
    company1: "Nodo Eafit",
  },
  {
    description:
      "MedellínJS nos ha permitido posicionarnos como referentes en el ecosistema tecnológico de la ciudad. Gracias al plan Oro, hemos impartido talleres y conectado directamente con desarrolladores apasionados. La comunidad es increíblemente receptiva, y el impacto en nuestra marca ha sido invaluable.",
    image: "/testimonials/03.jpg",
    name: "Alice Johnson",
    company: "Nodo Eafit",
    description1:
      "Ser patrocinadores de MedellínJS ha sido una de las mejores decisiones para nuestra marca. No solo hemos aumentado nuestra visibilidad en la comunidad tech, sino que también hemos conectado con talento excepcional. Los eventos son increíbles, y el equipo organizador siempre nos hace sentir parte de algo grande. ¡Totalmente recomendado!",
    image1: "/testimonials/03.jpg",
    name1: "Carlos Gómez",
    company1: "Nodo Eafit",
  },
];

export const communityTestimonials = [
  {
    image: "/community/35.jpg",
    name: "Juan Diego Silva",
    title: "Full stack web developer",
    des: "MedellínJS no solo conecta a la comunidad local, sino que también nos abre las puertas al mundo. ¡Gracias por traernos perspectivas globales!",
    image2: "/community/36.jpg",
    name2: "Jesús David Ramirez Sanchez",
    title2: "CTO",
    des2: "Gracias a MedellínJS, he conocido a personas increíbles con las que ya estoy colaborando en nuevos proyectos. ¡El networking aquí es invaluable!",
  },
  {
    image: "/community/29.jpg",
    name: "Edward Rojas Ortiz",
    title: "Estudiante Desarrollo web",
    des: "Hoy salí del evento con las pilas recargadas y listo para enfrentar nuevos desafíos. ¡Gracias, MedellínJS, por ser esa chispa que enciende nuestra pasión por la tecnología!",
    image2: "/community/30.jpg",
    name2: "Luis David Zea",
    title2: "Desarrollador Web",
    des2: "MedellínJS es más que un evento, es un espacio donde la colaboración y el apoyo mutuo son la norma. ¡Gracias por fomentar esta cultura tan especial!.",
  },
  {
    image: "/community/05.jpg",
    name: "Oscar Soto",
    title: "Developer",
    des: "Siempre tienen charlas de buena calidad y la comunidad es amibable.",
    image2: "/community/24.jpg",
    name2: "Alexander Londoño Espejo",
    title2: "Software Developer",
    des2: "Los expositores de hoy fueron increíbles. ¡Gracias, MedellínJS, por traer a los mejores talentos para compartir sus conocimientos con nosotros!",
  },
  {
    image: "/community/07.jpg",
    name: "Ana Monsalve",
    title: "Sofware Developer",
    des: "Un aplauso enorme para los organizadores de MedellínJS. Cada evento es una muestra de su dedicación y pasión por la comunidad. ¡Gracias por crear espacios donde todos podemos crecer juntos!",
    image2: "/community/08.jpg",
    name2: "Leonardo Salazar",
    title2: "Front End developer",
    des2: "Las charlas de hoy me dejaron con la mente llena de ideas y el corazón lleno de motivación. ¡Gracias, MedellínJS, por recordarme por qué amo ser parte de esta comunidad tech!",
  },
  {
    image: "/community/09.jpg",
    name: "Santiago Sanchez",
    title: "Ing. Sistemas",
    des: "No solo aprendí mucho en el evento de hoy, sino que también conocí a personas increíbles con las que ya estoy colaborando en nuevos proyectos. ¡Gracias, MedellínJS, por ser el puente que nos une!",
    image2: "/community/10.jpg",
    name2: "Maria Victoria Higuita",
    title2: "Asistente",
    des2: "Cada charla en MedellínJS es única y me encanta cómo abordan temas tan variados. Hoy aprendí sobre nuevas tecnologías y tendencias que no conocía. ¡Gracias por ampliar mis horizontes!",
  },
  {
    image: "/community/11.jpg",
    name: "Estefania Ceballos",
    title: "Ingeniera informática",
    des: "MedellínJS no es solo un evento, es una familia. Gracias por crear un espacio donde todos nos sentimos bienvenidos y apoyados. ¡Sigan siendo esa luz que guía a la comunidad tech!",
    image2: "/community/12.jpg",
    name2: "Daniela Alexandra",
    title2: "Web UI Developer",
    des2: "Cada evento de MedellínJS es una ventana al futuro de la tecnología. ¡Gracias por traernos charlas tan innovadoras y por mantenernos siempre un paso adelante!",
  },
  {
    image: "/community/13.jpg",
    name: "Salome Arboleda",
    title: "Estudiante",
    des: "Los expositores de hoy fueron increíbles. ¡Gracias, MedellínJS, por traer a los mejores talentos para compartir sus conocimientos con nosotros!",
    image2: "/community/14.jpg",
    name2: "Joseph Silva",
    title2: "Software Engineer",
    des2: "Gracias a las charlas de MedellínJS, he podido mejorar mis habilidades y avanzar en mi carrera. ¡Cada evento es una inversión en mi crecimiento profesional!",
  },
  {
    image: "/community/15.jpg",
    name: "Julian Bernal",
    title: "Software Engineer",
    des: "Me encanta cómo MedellínJS fomenta la inclusión y la diversidad en cada evento. ¡Gracias por crear un espacio donde todos podemos aprender y compartir sin barreras!",
    image2: "/community/16.jpg",
    name2: "Maicol Felipe Duque",
    title2: "Software Engineer",
    des2: "Todo estuvo perfectamente organizado, desde las charlas hasta el networking. ¡Gracias, MedellínJS, por siempre superar nuestras expectativas!",
  },
  {
    image: "/community/17.jpg",
    name: "Mariana Rodriguez",
    title: "Software Developer",
    des: "Hoy salí del evento con las pilas recargadas y listo para enfrentar nuevos desafíos. ¡Gracias, MedellínJS, por ser esa chispa que enciende nuestra pasión por la tecnología!",
    image2: "/community/18.jpg",
    name2: "Esteban Escobar",
    title2: "Mobile Developer",
    des2: "MedellínJS no es solo un evento, es un hogar para los amantes de la tecnología. ¡Gracias por hacernos sentir parte de algo tan especial!",
  },
  {
    image: "/community/19.jpg",
    name: "Juan Pablo Serna",
    title: "Estudiante",
    des: "Se nota la pasión y el esfuerzo que ponen en cada detalle. ¡Gracias, MedellínJS, por inspirarnos a ser mejores cada día!",
    image2: "/community/20.jpg",
    name2: "Alexander Chalarca Caro",
    title2: "Desarrollador de software",
    des2: "Gracias a MedellínJS, he conocido a personas increíbles con las que ya estoy colaborando en nuevos proyectos. ¡El networking aquí es invaluable!",
  },
  {
    image: "/community/21.jpg",
    name: "Felipe Ramirez",
    title: "Asistente",
    des: "Cada charla me mantiene al día con las últimas tendencias tecnológicas. ¡Gracias, MedellínJS, por ser mi fuente de conocimiento actualizado!",
    image2: "/community/22.jpg",
    name2: "Mariana Palacios Hinestroz",
    title2: "Backend Developer",
    des2: "Me encanta cómo MedellínJS aborda temas tan variados. Hoy aprendí sobre nuevas tecnologías que no conocía. ¡Gracias por ampliar mis horizontes!",
  },
  {
    image: "/community/23.jpg",
    name: "Angelica Arroyave",
    title: "Developer",
    des: "Las charlas de hoy me dejaron con la mente llena de ideas y el corazón lleno de motivación. ¡Gracias, MedellínJS, por recordarme por qué amo esta comunidad!",
    image2: "/community/06.jpg",
    name2: "Alejandro Hurtado Alvarez",
    title2: "CTO",
    des2: "¡Gracias, MedellínJS, por otra charla increíble! Aprendí cosas que nunca hubiera imaginado y salí con nuevas ideas para aplicar en mis proyectos. ¡Sigan inspirándonos!",
  },
  {
    image: "/community/25.jpg",
    name: "Santiago Bastidas",
    title: "Asistente",
    des: "Gracias a las charlas de MedellínJS, he podido mejorar mis habilidades y avanzar en mi carrera. ¡Cada evento es una inversión en mi crecimiento profesional!",
    image2: "/community/26.jpg",
    name2: "Alejandro Villegas",
    title2: "Software Engineer",
    des2: "Me encanta cómo MedellínJS fomenta la inclusión y la diversidad en cada evento. ¡Gracias por crear un espacio donde todos podemos aprender y compartir sin barreras!",
  },
  {
    image: "/community/27.jpg",
    name: "Luisa Fernanda Osorio",
    title: "Asistente",
    des: "Todo estuvo perfectamente organizado, desde las charlas hasta el networking. ¡Gracias, MedellínJS, por siempre superar nuestras expectativas!",
    image2: "/community/28.jpg",
    name2: "Andrea Alzate",
    title2: "Asistente",
    des2: "Cada evento de MedellínJS es una ventana al futuro de la tecnología. ¡Gracias por traernos charlas tan innovadoras y por mantenernos siempre un paso adelante.",
  },

  {
    image: "/community/03.jpg",
    name: "Johan Bustos",
    title: "Electronic engineer",
    des: "Los eventos de la comunidad son una excelente oportunidad para aprender y conocer gente nueva.",
    image2: "/community/04.jpg",
    name2: "Homer López",
    title2: "Frontend Developer",
    des2: "Lo bien organizado que esta todo y la calidad de las charlas es lo que más me gusta de MedellínJS. Siempre aprendo algo nuevo.",
  },
  {
    image: "/community/31.jpg",
    name: "Andres Hernandez",
    title: "Software Engineer",
    des: "Las charlas de hoy fueron de un nivel excepcional. ¡Gracias, MedellínJS, por siempre ofrecernos contenido de alta calidad y relevancia!",
    image2: "/community/32.jpg",
    name2: "Elena",
    title2: "Lead QA Engineer",
    des2: "Cada evento de MedellínJS es una oportunidad para aprender algo nuevo. ¡Gracias por ser esa plataforma que nos impulsa a crecer profesionalmente!",
  },
  {
    image: "/community/33.jpg",
    name: "Stiven Ramírez Arango",
    title: "Software Engineering Specialist",
    des: "The best part about Techwind is every time I pay my employees, my bank balance doesn't go down like it used to. Looking forward to spending this extra cash when I figure out why my card is being declined.",
    image2: "/community/34.jpg",
    name2: "Yunerkis Leal",
    title2: "Frontend Developer",
    des2: "El ambiente en MedellínJS es siempre tan acogedor y amigable. ¡Gracias por hacer que todos nos sintamos como en casa!.",
  },
  {
    image: "/community/01.jpg",
    name: "Juan Felipe Gomez",
    title: "Full Stack Developer",
    des: "Conocer gente que le gusta lo mismo que a uno y que está dispuesta a ayudar en lo que sea necesario es algo que no tiene precio. Gracias MedellínJS por tanto.",
    image2: "/community/02.jpg",
    name2: "Monica Echeverri",
    title2: "Ingeniera informática",
    des2: "Charlas muy interesantes, gente muy amable y un ambiente muy agradable. Me encanta MedellínJS.",
  },
];
