/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    media: Media
    speakers: Speaker
    events: Event
    members: Member
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    speakers: SpeakersSelect<false> | SpeakersSelect<true>
    events: EventsSelect<false> | EventsSelect<true>
    members: MembersSelect<false> | MembersSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale: null
  globals: {}
  globalsSelect: {}
  locale: null
  user: User & {
    collection: 'users'
  }
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * Usuarios con acceso al panel de administración
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  /**
   * Nombre del usuario administrativo
   */
  name: string
  /**
   * Rol del usuario en la plataforma (determina permisos en el admin)
   */
  role: 'admin' | 'organizer'
  updatedAt: string
  createdAt: string
  /**
   * Solo se permiten correos con dominio @medellinjs.org
   */
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  alt: string
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number
  /**
   * Nombre completo del speaker
   */
  name: string
  /**
   * Ejemplo: Senior Frontend Engineer, Tech Lead, etc.
   */
  role: string
  /**
   * Empresa donde trabaja actualmente (opcional)
   */
  company?: string | null
  /**
   * Foto de perfil del speaker
   */
  image: number | Media
  /**
   * Link a perfil social (Twitter, LinkedIn, GitHub, website personal)
   */
  link?: string | null
  /**
   * Biografía del speaker (puede incluir experiencia, logros, etc.)
   */
  bio?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  updatedAt: string
  createdAt: string
}
/**
 * Gestiona los eventos de MedellinJS
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number
  /**
   * Nombre descriptivo del evento
   */
  title: string
  /**
   * Categoría del evento según su formato y contenido
   */
  eventType: 'charla' | 'taller' | 'panel' | 'hackathon' | 'networking' | 'lightning-talks'
  /**
   * Se genera automáticamente desde el título. Usado en la URL del evento.
   */
  slug?: string | null
  /**
   * Descripción completa del evento. Soporta formato rico (negritas, enlaces, etc.)
   */
  description: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  /**
   * Imagen principal del evento para preview y detalle
   */
  previewImage?: (number | null) | Media
  /**
   * Fecha y hora cuando comienza el evento
   */
  startDate: string
  /**
   * Fecha y hora cuando termina el evento (opcional)
   */
  endDate?: string | null
  /**
   * Zona horaria del evento
   */
  timezone:
    | 'America/Bogota'
    | 'America/Mexico_City'
    | 'America/Argentina/Buenos_Aires'
    | 'America/Santiago'
    | 'Europe/Madrid'
  venue: {
    /**
     * Ej: Ruta N, Centro de Innovación, Virtual
     */
    name: string
    /**
     * Enlace a Google Maps con la ubicación exacta (opcional)
     */
    googleMapsUrl?: string | null
    /**
     * Detalles extra sobre el lugar: piso, sala, indicaciones, etc. (opcional)
     */
    extraInfo?: string | null
  }
  /**
   * Selecciona los speakers que participarán en este evento
   */
  speakers?: (number | Speaker)[] | null
  /**
   * Lista de personas que asistieron al evento (para mostrar en el detalle)
   */
  attendees?:
    | {
        name: string
        /**
         * URL de la foto de perfil del asistente (opcional)
         */
        avatarUrl?: string | null
        id?: string | null
      }[]
    | null
  /**
   * Si está marcado, el evento será visible para el público
   */
  isPublished?: boolean | null
  /**
   * Si está marcado, el evento aparecerá en la página principal
   */
  featured?: boolean | null
  /**
   * Número máximo de asistentes permitidos (opcional)
   */
  maxAttendees?: number | null
  /**
   * Etiquetas para categorizar el evento (React, Node.js, Workshop, etc.)
   */
  tags?:
    | {
        tag: string
        id?: string | null
      }[]
    | null
  updatedAt: string
  createdAt: string
}
/**
 * Miembros de la comunidad MedellinJS
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number
  /**
   * ID del usuario en NextAuth
   */
  nextAuthId?: string | null
  /**
   * Nombre completo del miembro
   */
  fullName: string
  /**
   * Email del miembro
   */
  email: string
  /**
   * URL de la imagen de perfil
   */
  profileImage?: string | null
  /**
   * Cargo o posición laboral
   */
  jobPosition: string
  /**
   * Nivel de experiencia
   */
  jobLevel: 'JUNIOR' | 'MID_LEVEL' | 'SENIOR' | 'LEAD' | 'STAFF' | 'PRINCIPAL'
  /**
   * Rol del miembro en la comunidad
   */
  role: 'MEMBER' | 'ORGANIZER' | 'SPEAKER'
  /**
   * Biografía o descripción del miembro (opcional)
   */
  bio?: string | null
  /**
   * Redes sociales del miembro (opcional)
   */
  socialLinks?: {
    twitter?: string | null
    linkedin?: string | null
    github?: string | null
    website?: string | null
  }
  /**
   * Fecha en que se unió a la comunidad
   */
  joinedAt?: string | null
  /**
   * Miembro activo en la comunidad
   */
  isActive?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'media'
        value: number | Media
      } | null)
    | ({
        relationTo: 'speakers'
        value: number | Speaker
      } | null)
    | ({
        relationTo: 'events'
        value: number | Event
      } | null)
    | ({
        relationTo: 'members'
        value: number | Member
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T
  role?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T
  role?: T
  company?: T
  image?: T
  link?: T
  bio?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T
  eventType?: T
  slug?: T
  description?: T
  previewImage?: T
  startDate?: T
  endDate?: T
  timezone?: T
  venue?:
    | T
    | {
        name?: T
        googleMapsUrl?: T
        extraInfo?: T
      }
  speakers?: T
  attendees?:
    | T
    | {
        name?: T
        avatarUrl?: T
        id?: T
      }
  isPublished?: T
  featured?: T
  maxAttendees?: T
  tags?:
    | T
    | {
        tag?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  nextAuthId?: T
  fullName?: T
  email?: T
  profileImage?: T
  jobPosition?: T
  jobLevel?: T
  role?: T
  bio?: T
  socialLinks?:
    | T
    | {
        twitter?: T
        linkedin?: T
        github?: T
        website?: T
      }
  joinedAt?: T
  isActive?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
